<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto

namespace GPBMetadata;

class Grpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x01\x0A\x0Agrpc.proto\x12\x04grpc\"#\x0A\x06HiUser\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0B\x0A\x03sex\x18\x02 \x01(\x05\"6\x0A\x07HiReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\x12\x1A\x0A\x04user\x18\x02 \x01(\x0B2\x0C.grpc.HiUser2/\x0A\x02Hi\x12)\x0A\x08SayHello\x12\x0C.grpc.HiUser\x1A\x0D.grpc.HiReply\"\x00b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

