<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto

namespace GPBMetadata;

class Grpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A~\x0A\x0Agrpc.proto\x12\x04grpc\"\x1A\x0A\x07Request\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\"\x18\x0A\x05Reply\x12\x0F\x0A\x07message\x18\x01 \x01(\x092,\x0A\x04User\x12\$\x0A\x04Info\x12\x0D.grpc.Request\x1A\x0B.grpc.Reply\"\x00b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

